local momo = {
    "a",
    "advanced-plastics",
    "advanced-wire",
    "atc",
    "atomic-emission-point",
    "atomic-fusion",
    "b1",
    "b2",
    "b3",
    "b4",
    "b5",
    "bio-desert",
    "bio-grade-1",
    "bio-grade-2",
    "bio-grade-3",
    "bio-swamp",
    "bio-temp",
    "bronze-pack",
    "building-pack",
    "burner-assembling-machine",
    "coil",
    "momo-electronics-control-a-red",
    "momo-electronics-control-b-gray",
    "momo-electronics-control-c-blue",
    "momo-electronics-control-d-green",
    "cpy",
    "cyan-sci",
    "dark-chip",
    "e",
    "green-sci",
    "momo-electronics-junction-green",
    "momo-electronics-junction-red",
    "logistic-express",
    "momo-electronics-memory-a",
    "momo-electronics-memory-a-2",
    "momo-electronics-memory-a-3",
    "momo-electronics-memory-b",
    "momo-electronics-memory-c",
    "momo-oil-pack",
    "momo-vial",
    "movement-pack",
    "plate-pack-1",
    "pre-cyan-sci",
    "pre-dark-sci",
    "pre-high-sci",
    "product-sci",
    "py-cyan",
    "py-gold",
    "py-green",
    "py-nxag-matrix",
    "py-pro",
    "py-superconductor",
    "red-sci",
    "sct-2",
    "sct-3",
    "sct-gun",
    "sct-high",
    "sct-logistic",
    "sct-production",
}

local Items = {items = {}}

for _, item in pairs(momo) do
  Items.items[item] = {}
end

return Items
